name: CI/CD

on:
  push:
    branches:
      - master  # Ejecutar en push a la rama master
  pull_request:
    branches:
      - master  # Ejecutar en pull requests a la rama master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Build Docker image
      run: |
        docker build -t your-docker-username/your-image-name:latest .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker push your-docker-username/your-image-name:latest